'use client';
import {useEffect,useState} from 'react';
import {Apple,LayoutDashboard,Trees,Users,Package,Sprout,UserRound,Truck,NotebookPen,Megaphone,ChartNoAxesCombined,ListTodo,Settings,Plus,ArrowUpRight,ArrowRight,Search,Leaf,ChevronRight,Download,Check,CalendarDays} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {Toaster,toast} from 'sonner';
import {seed,metrics,adopt,advance,renew,revenueSeries} from '../store';
const nav=['首页总览','果树管理','认领用户','认领套餐','成长记录','果农管理','订单交付','内容运营','营销活动','经营数据','待办事项','项目设置'];
const icons=[LayoutDashboard,Trees,Users,Package,Sprout,UserRound,Truck,NotebookPen,Megaphone,ChartNoAxesCombined,ListTodo,Settings];
function Pick({value,onChange,options}:any){return <Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue>{value}</SelectValue></SelectTrigger><SelectContent>{options.map((x:string)=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>}
function DataTable({heads,rows}:any){return <Table><TableHeader><TableRow>{heads.map((h:string)=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r:any[],i:number)=><TableRow key={i}>{r.map((c,j)=><TableCell key={j}>{c}</TableCell>)}</TableRow>)}</TableBody></Table>}
export default function App(){const [db,setDb]=useState<any>(seed),[ready,setReady]=useState(false),[page,setPage]=useState(0),[query,setQuery]=useState(''),[filter,setFilter]=useState('全部状态'),[modal,setModal]=useState(''),[selected,setSelected]=useState('A001'),[userId,setUserId]=useState(1),[form,setForm]=useState<any>({}),[limit,setLimit]=useState(20);
useEffect(()=>{try{const x=localStorage.getItem('shanli-v1');if(x)setDb(JSON.parse(x));}catch{toast.error('本地记录无法读取，已载入演示数据')}setReady(true);const n=Number(location.hash.slice(1));if(n>=0&&n<12)setPage(n)},[]);
useEffect(()=>{if(ready)try{localStorage.setItem('shanli-v1',JSON.stringify(db))}catch{toast.error('存储空间不足，请导出数据备份')}},[db,ready]);
function go(n:number){setPage(n);location.hash=String(n);setQuery('');setFilter('全部状态');setLimit(20)}
function open(name:string,f:any={}){setForm(f);setModal(name)}
function save(next:any,msg='已保存'){setDb(next);toast.success(msg);setModal('')}
const m=metrics(db),tree=db.trees.find((t:any)=>t.id===selected),usr=db.users.find((u:any)=>u.id===userId);
const input=(name:string,label:string,type='text',required=true)=><label className="field">{label}<input type={type} min={type==='number'?1:undefined} required={required} value={form[name]??''} onChange={e=>setForm({...form,[name]:e.target.value})}/></label>;
const pick=(name:string,label:string,opts:string[])=><label className="field">{label}<Pick value={form[name]||opts[0]} options={opts} onChange={(v:string)=>setForm({...form,[name]:v})}/></label>;
function submit(e:any){e.preventDefault();try{if(modal==='新增认领'){save(adopt(db,form),'认领成功，果树与用户已关联')}else if(modal==='新增成长记录'){save({...db,records:[{...form,id:Date.now(),tree:form.tree||selected,stage:form.stage||'萌芽'},...db.records]},'成长记录已更新')}else if(modal==='创建交付订单'){if(db.orders.some((o:any)=>o.tree===selected&&o.year===2026))throw Error('本年度已存在交付订单');if(!tree.user)throw Error('请先认领果树');save({...db,orders:[{id:'SL'+Date.now().toString().slice(-7),tree:selected,user:tree.user,year:2026,status:tree.stage==='成熟'?'待采摘':'待成熟',...form,method:form.method||'邮寄'},...db.orders]})}else if(modal==='编辑套餐'||modal==='新增套餐'){const p={...form,price:Number(form.price),id:form.id||Date.now()};save({...db,plans:form.id?db.plans.map((x:any)=>x.id===p.id?p:x):[...db.plans,p]})}else if(modal==='物流信息'){save({...db,orders:db.orders.map((o:any)=>o.id===form.id?{...o,...form}:o)})}else if(modal==='新建内容'){save({...db,contents:[{...form,platform:form.platform||'朋友圈',type:form.type||'果园日常',status:'待发布',views:0,leads:0,sales:0,id:Date.now()},...db.contents]})}else if(modal==='新增待办'){save({...db,tasks:[...db.tasks,{...form,done:false,id:Date.now()}]})}else if(modal==='续领确认'){save(renew(db,userId,Number(form.amount)),'次年续领已记录，历史已保留')}else if(modal==='项目设置'){save({...db,project:form})}}catch(err:any){toast.error(err.message)}}
const badge=(s:string)=><span className={'badge '+(['待认领','待成熟','待包装','待发布'].includes(s)?'amber':'')}>{s}</span>;
const detail=(id:string)=>{setSelected(id);setModal('果树详情')};
const treeRows=db.trees.filter((t:any)=>(filter==='全部状态'||(filter==='待认领'?!t.user:filter==='已认领'?!!t.user:t.stage===filter))&&(t.id+' '+t.orchard+' '+t.farmer).toLowerCase().includes(query.toLowerCase()));
const tasks=<div className="task-list">{db.tasks.filter((t:any)=>page===10||!t.done).slice(0,page===10?100:5).map((t:any)=><button key={t.id} className={'task '+(t.done?'done':'')} onClick={()=>setDb({...db,tasks:db.tasks.map((x:any)=>x.id===t.id?{...x,done:!x.done}:x)})}><span className="check">{t.done&&<Check size={13}/>}</span><span>{t.title}<small>{t.date} · 项目运营</small></span><ChevronRight size={15}/></button>)}</div>;
const vals=revenueSeries(db),max=Math.max(50000,...vals),pts=vals.map((v:number,i:number)=>`${i*110},${165-v/max*150}`).join(' ');
const chart=<div className="chart"><div className="chart-y">{[max,Math.round(max*.66),Math.round(max*.33),0].map(v=><span key={v}>{v.toLocaleString()}</span>)}</div><div className="plot"><svg viewBox="0 0 660 180" preserveAspectRatio="none" aria-label="三月至九月累计认领收入趋势"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#52784b" stopOpacity=".18"/><stop offset="1" stopColor="#52784b" stopOpacity="0"/></linearGradient></defs>{[15,65,115,165].map(y=><line key={y} x1="0" x2="660" y1={y} y2={y} stroke="#e9ece4" strokeDasharray="4 5"/>)}<polygon points={'0,180 '+pts+' 660,180'} fill="url(#area)"/><polyline points={pts} stroke="#53774a" strokeWidth="3" fill="none"/>{vals.map((v:number,i:number)=><circle key={i} cx={i*110} cy={165-v/max*150} r="4" fill="#53774a"><title>{`${i + 3}月累计 ¥${v}`}</title></circle>)}</svg><div className="months">{['3月','4月','5月','6月','7月','8月','9月'].map(x=><span key={x}>{x}</span>)}</div></div></div>;
return <SidebarProvider><Sidebar className="side"><SidebarHeader><div className="brand"><span><Apple size={25}/></span><div>山里有棵树<small>SHANLI · ADOPT A TREE</small></div></div></SidebarHeader><SidebarContent><div className="nav-caption">项目工作台</div><SidebarMenu>{nav.map((n,i)=>{const Icon=icons[i];return <SidebarMenuItem key={n}><SidebarMenuButton className="nav-item" isActive={page===i} onClick={()=>go(i)}><Icon size={19}/><span>{n}</span>{i===10&&<b>{db.tasks.filter((t:any)=>!t.done).length}</b>}</SidebarMenuButton></SidebarMenuItem>})}</SidebarMenu></SidebarContent><SidebarFooter><div className="season"><Leaf size={19}/><span>好好种树，慢慢相伴<small>2026 认领季 · 果实着色期</small></span></div><div className="operator"><span>林</span><div>林小山<small>项目管理员</small></div><Settings size={17}/></div></SidebarFooter></Sidebar><main className="workspace"><header className="topbar"><div><SidebarTrigger/><span>工作台</span><ChevronRight size={14}/><b>{nav[page]}</b></div><div><span className="demo-dot"/>模拟数据演示<em/><CalendarDays size={15}/>2026年9月14日</div></header><div className="main-content"><div className="page-head"><div><div className="eyebrow">{page===0?'从一棵树开始，让美好发生':'山里苹果树认领计划 / 2026'}</div><h1>{page===0?db.project.name:nav[page]}</h1><p>{page===0?'让城市里的人，在山里拥有一棵自己的苹果树。':['','每一棵树，都有自己的故事与主人。','连接一位主人，开启一年的陪伴。','让不同的期待，都有合适的认领方式。','把山里的变化，带到每一位主人身边。','照顾好树，也照顾好种树的人。','从枝头到手中，让每一份期待准时抵达。','持续记录真实的山里生活。','从第一百位主人，走向长久的陪伴。','用数据看见每一份耕耘的价值。','今天的小事，是一年丰收的开始。','管理项目与演示数据。'][page]}</p></div><div className="head-actions">{page===0&&<button className="btn" onClick={()=>go(9)}><ChartNoAxesCombined size={16}/>经营报告</button>}<button className="btn primary" onClick={()=>page===3?open('新增套餐'):page===4?open('新增成长记录',{tree:selected,date:'2026-09-14'}):page===7?open('新建内容',{date:'2026-09-14'}):page===10?open('新增待办',{date:'2026-09-14'}):open('新增认领',{plan:db.plans[1].name,tree:db.trees.find((t:any)=>!t.user)?.id,date:'2026-09-14'})}><Plus size={17}/>{page===3?'新增套餐':page===4?'记录成长':page===7?'新建内容':page===10?'新增待办':'新增认领'}</button></div></div>
{page===0&&<><div className="overview-grid"><section className="stats-grid">{[['果树总数量',m.total,'棵',Trees,'已建立独立果树档案'],['已认领果树',m.claimed,'棵',Sprout,`认领进度 ${m.rate}%`],['待认领果树',m.available,'棵',Leaf,'等待遇见它的主人'],['当前认领用户',m.users,'人',Users,'一起等待山里的丰收'],['本年度认领收入',m.revenue.toLocaleString(),'元',ChartNoAxesCombined,'2026 年累计认领金额'],['苹果预计产量',m.yield.toLocaleString(),'斤',Apple,'以实际采收产量为准'],['已完成订单',m.completed,'单',Package,'已送达的山里心意'],['用户续领率',m.renewal,'%',ArrowUpRight,'已续领 / 上年到期用户']].map(([label,val,unit,Icon,note]:any)=><div className="stat" key={label}><div>{label}<Icon size={17}/></div><strong>{val}<small>{unit}</small></strong><p>{note}</p></div>)}</section><section className="orchard-card"><img src="/orchard.jpg" alt="红苹果挂在果园的枝头，果园示意照片"/><div className="orchard-overlay"><span>山里的九月</span><h2>苹果红了，<br/>相见的日子近了。</h2><p>在枝头，收藏一整个秋天</p><button onClick={()=>go(4)}>去看看果树的近况 <ArrowRight size={16}/></button></div></section></div><div className="dashboard-middle"><section className="panel"><div className="panel-heading"><h2>认领收入趋势 <small>累计收入 · 元</small></h2><span className="period">2026年 3月 — 9月</span></div><div className="chart-summary"><strong>¥ {m.revenue.toLocaleString()}</strong><span>这一年的陪伴，正在慢慢生长</span><i>● 认领收入</i></div>{chart}</section><section className="panel activity"><div className="panel-heading"><h2>第一阶段 · 正在进行</h2><span className="badge">招募中</span></div><div className="activity-icon"><Trees size={27}/></div><h3>寻找100位苹果树主人</h3><p>让100棵苹果树，连接100份城市里的牵挂。</p><div className="progress-label"><strong>{m.claimed}<small> / 100 棵</small></strong><span>{Math.min(m.claimed,100)}%</span></div><Progress value={Math.min(m.claimed,100)}/><div className="activity-bottom"><span>还差 {Math.max(0,100-m.claimed)} 棵，完成第一阶段目标</span><button onClick={()=>go(8)}>查看活动 <ArrowUpRight size={15}/></button></div></section></div><div className="dashboard-bottom"><section className="panel"><div className="panel-heading"><h2>最近认领 <small>每一次认领，都是信任</small></h2><button onClick={()=>go(2)}>全部用户 <ArrowRight size={15}/></button></div><DataTable heads={['认领人','果树编号','认领套餐','认领日期','支付金额']} rows={[...db.users].sort((a:any,b:any)=>b.date.localeCompare(a.date)).slice(0,4).map((u:any)=>[<button className="person" onClick={()=>{setUserId(u.id);setModal('用户档案')}}><span>{u.name[0]}</span>{u.name}</button>,<button className="link" onClick={()=>detail(u.tree)}>{u.tree}</button>,u.plan,u.date,<b>¥{u.amount}</b>])}/></section><section className="panel"><div className="panel-heading"><h2>今日待办 <small>{db.tasks.filter((t:any)=>!t.done).length} 项</small></h2><button onClick={()=>go(10)}>全部 <ArrowRight size={15}/></button></div>{tasks}</section></div></>}
{page===1&&<section className="panel"><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="搜索果树编号、果园、果农" value={query} onChange={e=>{setQuery(e.target.value);setLimit(20)}}/></div><Pick value={filter} onChange={setFilter} options={['全部状态','待认领','已认领','生长中','成熟','已完成']}/><span>共 {treeRows.length} 棵</span></div><DataTable heads={['果树编号','所属果园 / 果农','品种 / 树龄','认领状态','生长阶段','预计产量','认领人','操作']} rows={treeRows.slice(0,limit).map((t:any)=>[<b>{t.id}</b>,t.orchard+' / '+t.farmer,t.variety+' / '+t.age+'年',badge(t.user?'已认领':'待认领'),badge(t.stage),t.yield+'斤',db.users.find((u:any)=>u.id===t.user)?.name||'—',<button className="link" onClick={()=>detail(t.id)}>查看档案 →</button>])}/>{treeRows.length>limit&&<button className="btn load" onClick={()=>setLimit(limit+40)}>加载更多果树</button>}{!treeRows.length&&<p className="empty">没有符合条件的果树，请调整搜索条件。</p>}</section>}
{page===2&&<section className="panel"><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="搜索姓名、城市、电话或果树" value={query} onChange={e=>setQuery(e.target.value)}/></div><span>共 {db.users.length} 位认领人</span></div><DataTable heads={['认领人','城市 / 联系方式','果树编号','套餐','支付金额','交付方式','用户来源','操作']} rows={db.users.filter((u:any)=>(u.name+u.city+u.phone+u.tree).includes(query)).map((u:any)=>[u.name,u.city+' / '+u.phone,u.tree,u.plan,'¥'+u.amount,u.method,u.source,<button className="link" onClick={()=>{setUserId(u.id);setModal('用户档案')}}>完整档案 →</button>])}/></section>}
{page===3&&<div className="plans">{db.plans.map((p:any,i:number)=><section className={'panel plan '+(i===1?'featured':'')} key={p.id}>{i===1&&<span className="recommend">最受家庭欢迎</span>}<Leaf size={28}/><h2>{p.name}</h2><strong>¥{p.price}<small> / 年</small></strong><p>{p.note}</p><ul>{p.benefits.split('；').map((b:string)=><li key={b}><Check size={16}/>{b}</li>)}</ul><button className="btn" onClick={()=>open('编辑套餐',p)}>编辑套餐</button></section>)}</div>}
{page===4&&<section className="panel records"><div className="toolbar"><h2>一棵苹果树的一年</h2><Pick value={selected} onChange={setSelected} options={db.trees.map((t:any)=>t.id)}/><button className="link" onClick={()=>detail(selected)}>查看果树档案 →</button></div><div className="timeline">{db.records.filter((r:any)=>r.tree===selected).map((r:any)=><article key={r.id}><span className="timeline-dot"/><time>{r.date}</time><h3>{r.stage}</h3><p>{r.text}</p>{r.media&&(r.media.startsWith('data:video')?<video controls src={r.media}/>:<img src={r.media} alt={r.stage+'成长照片'}/>)}</article>)}{!db.records.some((r:any)=>r.tree===selected)&&<p className="empty">还没有成长记录，记录这棵树的第一个瞬间吧。</p>}</div></section>}
{page===5&&<div className="plans">{['张叔','李婶','王大伯'].map((f,i)=>{const ts=db.trees.filter((t:any)=>t.farmer===f);return <section className="panel plan" key={f}><div className="farmer-avatar">{f[0]}</div><h2>{f}</h2><p>{[58,56,62][i]} 岁 · {i+1}号果园</p><dl><dt>联系电话</dt><dd>1380000000{i+1}</dd><dt>管理果树</dt><dd>{ts.length} 棵</dd><dt>已认领</dt><dd>{ts.filter((t:any)=>t.user).length} 棵</dd><dt>预计产量</dt><dd>{ts.reduce((s:number,t:any)=>s+t.yield,0)} 斤</dd><dt>预计收益</dt><dd>¥{Math.round(ts.reduce((s:number,t:any)=>s+(db.users.find((u:any)=>u.id===t.user)?.amount||0),0)*.6)}</dd><dt>实际收益</dt><dd>¥0 · 尚未结算</dd></dl><button className="btn" onClick={()=>{go(1);setQuery(f)}}>查看负责果树</button></section>})}</div>}
{page===6&&<section className="panel"><div className="toolbar"><h2>交付订单 · {db.orders.length}</h2><Pick value={filter} onChange={setFilter} options={['全部状态','待成熟','待采摘','待包装','待发货','已发货','已签收','已完成']}/></div><DataTable heads={['订单 / 果树','认领人','交付方式','重量 / 包装','收货地址','物流','状态','操作']} rows={db.orders.filter((o:any)=>filter==='全部状态'||o.status===filter).map((o:any)=>[<><b>{o.id}</b><small>{o.tree}</small></>,db.users.find((u:any)=>u.id===o.user)?.name,o.method,o.weight+'斤 / '+o.pack,o.address||'到园采摘',o.tracking||'—',badge(o.status),<div className="row-actions"><button className="link" onClick={()=>open('物流信息',o)}>物流信息</button>{o.status!=='已完成'&&<button className="link" onClick={()=>{try{setDb(advance(db,o.id));toast.success('交付状态已更新')}catch(e:any){toast.error(e.message)}}}>推进交付 →</button>}</div>])}/></section>}
{page===7&&<section className="panel"><DataTable heads={['选题','内容类型','平台','计划时间','状态','浏览 / 咨询 / 成交','操作']} rows={db.contents.map((c:any)=>[<button className="link" onClick={()=>open('内容详情',c)}>{c.title}</button>,c.type,c.platform,c.date,badge(c.status),`${c.views} / ${c.leads} / ${c.sales}`,<button className="link" onClick={()=>setDb({...db,contents:db.contents.map((x:any)=>x.id===c.id?{...x,status:x.status==='已发布'?'待发布':'已发布'}:x)})}>{c.status==='已发布'?'撤回状态':'标记已发布'}</button>])}/></section>}
{page===8&&<section className="panel campaign"><span className="badge">市场验证 · 进行中</span><h2>寻找100位苹果树主人</h2><p>先让100棵真实的苹果树，找到愿意长期相伴的主人。</p><Progress value={Math.min(m.claimed,100)}/><div className="mini-stats">{[['计划认领','100 棵'],['已认领',m.claimed+' 棵'],['咨询人数','240 人'],['成交人数',m.users+' 人'],['转化率',(m.users/240*100).toFixed(1)+'%'],['认领收入','¥'+m.revenue.toLocaleString()]].map(([a,b])=><div key={a}>{a}<strong>{b}</strong></div>)}</div><p>2026.03.01 — 2026.10.31 · 朋友圈 / 小红书 / 朋友推荐</p><button className="btn primary" onClick={()=>open('新增认领',{date:'2026-09-14'})}>登记活动认领</button></section>}
{page===9&&<><div className="analytics-stats">{[['认领收入','¥'+m.revenue.toLocaleString()],['平均客单价','¥'+Math.round(m.revenue/m.users)],['果农预计分成','¥'+Math.round(m.revenue*.6).toLocaleString()],['项目预计毛利润','¥'+Math.round(m.revenue*.4-db.costs.pack-db.costs.logistics-db.costs.marketing-db.costs.service).toLocaleString()]].map(([a,b])=><div className="stat" key={a}><div>{a}</div><strong>{b}</strong></div>)}</div><section className="panel"><div className="panel-heading"><h2>认领收入变化</h2><span>2026 年累计收入</span></div>{chart}</section><div className="dashboard-middle"><section className="panel"><div className="panel-heading"><h2>成本与收益测算</h2><small>模拟预算 · 未结算</small></div><DataTable heads={['项目','金额 / 指标']} rows={[[ '包装成本','¥'+db.costs.pack],['物流成本','¥'+db.costs.logistics],['营销成本','¥'+db.costs.marketing],['用户服务成本','¥'+db.costs.service],['单用户服务成本','¥'+(db.costs.service/m.users).toFixed(1)],['已认领单棵树收入','¥'+(m.revenue/m.claimed).toFixed(1)],['平均单棵产量',m.yield/m.total+'斤'],['转介绍率',(db.users.filter((u:any)=>u.source==='朋友推荐').length/m.users*100).toFixed(1)+'%'],['次年续领率',m.renewal+'%']]}/></section><section className="panel notes"><h2>统计口径</h2><p>认领收入来自2026年认领历史；次年续领金额归入2027年，不重复计入本年度。</p><p>果农预计分成按认领收入的60%估算。项目预计毛利润 = 认领收入 − 果农分成 − 包装 − 物流 − 营销 − 服务成本。</p><p>续领率 = 已续领上年用户 / 上年到期用户。产量及成本为演示预算，以实际结算为准。</p></section></div></>}
{page===10&&<section className="panel">{tasks}</section>}
{page===11&&<section className="panel notes"><h2>{db.project.name}</h2><p>负责人：{db.project.owner} · 运营年度：2026</p><p>当前为模拟运营工作台，记录保存在当前浏览器。可以导出完整数据进行备份；尚未接入真实支付、短信和快递服务。</p><div className="row-actions"><button className="btn" onClick={()=>open('项目设置',db.project)}>编辑项目信息</button><button className="btn" onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='山里苹果树-运营备份.json';a.click();URL.revokeObjectURL(a.href)}}><Download size={16}/>导出数据</button></div></section>}
<footer>山里有棵树 <span>把一年的期待，种进山里。</span><small>演示工作台 · 数据保存在当前浏览器</small></footer></div></main>
<Dialog open={!!modal} onOpenChange={o=>{if(!o)setModal('')}}><DialogContent className="app-dialog"><DialogTitle>{modal}</DialogTitle>
{modal==='果树详情'?<div className="details"><div className="detail-banner"><Trees size={38}/><div><h2>{tree.id} · {tree.variety}</h2><p>{tree.orchard} / {tree.farmer}照料</p></div>{badge(tree.user?'已认领':'待认领')}</div><dl>{[['树龄',tree.age+'年'],['预计产量',tree.yield+'斤'],['预计成熟','2026年9月底'],['生长阶段',tree.stage],['认领人',db.users.find((u:any)=>u.id===tree.user)?.name||'等待认领'],['认领日期',db.users.find((u:any)=>u.id===tree.user)?.date||'—']].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><div className="row-actions">{!tree.user?<button className="btn primary" onClick={()=>open('新增认领',{tree:selected,date:'2026-09-14'})}>认领这棵树</button>:<button className="btn primary" onClick={()=>open('创建交付订单',{weight:20,pack:'5斤礼盒 × 4',address:db.users.find((u:any)=>u.id===tree.user)?.address,method:db.users.find((u:any)=>u.id===tree.user)?.method})}>创建交付订单</button>}<button className="btn" onClick={()=>open('新增成长记录',{tree:selected,date:'2026-09-14'})}>添加成长记录</button>{tree.stage!=='成熟'&&tree.stage!=='已完成'&&<button className="btn" onClick={()=>{setDb({...db,trees:db.trees.map((t:any)=>t.id===selected?{...t,stage:'成熟'}:t)});toast.success('已标记成熟')}}>标记成熟</button>}</div><h3>成长时间线</h3>{db.records.filter((r:any)=>r.tree===selected).map((r:any)=><p key={r.id} className="history"><b>{r.date} · {r.stage}</b>{r.text}</p>)}</div>:modal==='用户档案'?<div className="details"><h2>{usr.name} <span className="badge">{usr.city}</span></h2><dl>{[['电话',usr.phone],['微信',usr.wechat||'未填写'],['果树',usr.history.filter((h:any)=>h.year===2026).map((h:any)=>h.tree).join('、')],['套餐',usr.plan],['交付方式',usr.method],['采摘计划',usr.method==='到园采摘'?'计划到园':'暂无'],['地址',usr.address||'无需邮寄'],['来源',usr.source],['续领意愿',usr.willing||'待回访']].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><h3>完整认领历史</h3>{usr.history.map((h:any,i:number)=><p className="history" key={i}><b>{h.year} 年 · {h.tree} · ¥{h.amount}</b>{h.date} · {h.status}</p>)}<button className="btn primary" onClick={()=>{setUserId(usr.id);open('续领确认',{amount:db.plans.find((p:any)=>p.name===usr.plan)?.price||499})}}>登记次年续领</button><p className="muted">登记已确认的续领，不会自动发送消息或扣款。</p></div>:modal==='内容详情'?<div className="notes"><h2>{form.title}</h2><p>{form.text||'文案待完善'}</p><p>{form.platform} · {form.date} · {form.status}</p></div>:<form onSubmit={submit} className="form-grid">
{modal==='新增认领'&&<>{input('name','姓名')}{input('phone','联系电话','tel')}{input('city','所在城市')}{input('wechat','微信','text',false)}{pick('plan','认领套餐',db.plans.map((p:any)=>p.name))}{pick('tree','分配果树',db.trees.filter((t:any)=>!t.user).map((t:any)=>t.id))}{input('date','认领日期','date')}{pick('method','交付方式',['邮寄','到园采摘'])}{input('address','苹果收货地址','text',form.method!=='到园采摘')}{pick('source','用户来源',['朋友圈','朋友推荐','小红书','抖音','视频号','企业客户','老客户'])}<p className="form-note">确认后按套餐金额登记认领并关联果树。此为模拟支付登记。</p></>}
{modal==='新增成长记录'&&<>{pick('tree','果树编号',db.trees.map((t:any)=>t.id))}{input('date','记录日期','date')}{pick('stage','成长阶段',['萌芽','开花','疏果','套袋','膨大','着色','成熟','采摘'])}{input('text','成长说明')}<label className="field full">照片 / 视频（不超过2MB）<input type="file" accept="image/*,video/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2*1024*1024){toast.error('演示存储限制为2MB，请选择较小文件');return}const r=new FileReader();r.onload=()=>setForm((old:any)=>({...old,media:r.result}));r.readAsDataURL(f)}}/></label></>}
{modal==='创建交付订单'&&<>{pick('method','交付方式',['邮寄','到园采摘'])}{input('weight','苹果重量（斤）','number')}{input('pack','包装规格')}{input('address','收货地址','text',form.method!=='到园采摘')}</>}
{(modal==='编辑套餐'||modal==='新增套餐')&&<>{input('name','套餐名称')}{input('price','年度价格（元）','number')}{input('note','套餐简介')}{input('benefits','权益（使用中文分号；分隔）')}</>}
{modal==='物流信息'&&<>{input('address','收货地址','text',form.method!=='到园采摘')}{input('carrier','快递公司','text',form.method!=='到园采摘')}{input('tracking','快递单号','text',form.method!=='到园采摘')}{input('shipDate','发货 / 采摘日期','date',form.method!=='到园采摘')}</>}
{modal==='新建内容'&&<>{input('title','选题')}{pick('type','内容类型',['果园日常','果树成长记录','果农故事','苹果知识','乡村生活','用户认领故事','采摘活动','苹果成熟记录'])}{pick('platform','发布平台',['朋友圈','小红书','抖音','视频号','公众号','微信群'])}{input('date','发布时间','date')}{input('text','内容文案')}</>}
{modal==='新增待办'&&<>{input('title','待办事项')}{input('date','计划日期','date')}</>}
{modal==='续领确认'&&<>{input('amount','2027年续领金额（元）','number')}<p>为 {usr?.name} 保留 {usr?.tree}，增加2027年认领历史。</p></>}
{modal==='项目设置'&&<>{input('name','项目名称')}{input('owner','项目负责人')}</>}
<div className="form-footer"><button type="button" className="btn" onClick={()=>setModal('')}>取消</button><button className="btn primary" type="submit">确认保存 <Check size={16}/></button></div></form>}
</DialogContent></Dialog><Toaster position="top-center" richColors/></SidebarProvider>}
