export const plans=[{id:1,name:'体验认领',price:299,note:'一份来自山里的小小期待',benefits:'苹果树认领权益；专属果树编号；果树成长照片；苹果礼盒；成熟后邮寄'},{id:2,name:'家庭认领',price:499,note:'和家人一起，等待一年的甜',benefits:'一棵苹果树认领权益；专属认领牌；全年成长记录；约20斤苹果；到果园采摘；成熟后邮寄'},{id:3,name:'深度认领',price:699,note:'在山里，拥有一份更深的牵挂',benefits:'一棵专属苹果树；定制挂牌；全年照片和短视频；20～30斤苹果；家庭采摘体验；果园活动参与权'}];
const id=(i:number)=>'A'+String(i).padStart(3,'0');
const users=Array.from({length:82},(_,i)=>{const p=plans[i<26?0:i<62?1:2];return {id:i+1,name:i===0?'王女士':['陈晓','刘女士','李明','周女士','张先生','赵晓雨','许女士','林先生'][i%8]+(i>7?' '+(i+1):''),phone:'1380000'+String(i+1).padStart(4,'0'),wechat:'shanli_demo_'+(i+1),city:['杭州','上海','北京','南京','苏州'][i%5],tree:id(i+1),plan:p.name,amount:p.price,date:i===0?'2026-03-18':`2026-09-${String(i%13+1).padStart(2,'0')}`,method:i%5===0?'到园采摘':'邮寄',address:i%5===0?'':['杭州','上海','北京','南京','苏州'][i%5]+'市 幸福路88号（演示地址）',source:['朋友圈','朋友推荐','小红书','抖音','视频号','企业客户','老客户'][i%7],willing:i%3===0?'愿意续领':'待回访',history:[...(i<20?[{year:2025,tree:id(i+1),amount:499,date:'2025-03-20',status:'已完成'}]:[]),{year:2026,tree:id(i+1),amount:p.price,date:'2026-03-18',status:'陪伴中'},...(i<5?[{year:2026,tree:id(83+i),amount:499,date:'2026-04-20',status:'陪伴中'}]:[])]}});
// 87 contracts: 26 × 299 + 41 × 499 + 20 × 699 = 42,213.
export const seed={project:{name:'山里苹果树认领计划',owner:'林小山'},plans,users,trees:Array.from({length:500},(_,i)=>({id:id(i+1),orchard:(i%3+1)+'号果园',farmer:['张叔','李婶','王大伯'][i%3],age:12+i%6,variety:'红富士',yield:80,user:i<82?i+1:i<87?i-81:0,stage:i>=15&&i<25?'成熟':'生长中'})),records:[{id:1,tree:'A001',date:'2026-09-10',stage:'着色',text:'秋天的阳光让果子一天天红起来。张叔说，今年的果子糖分积累得很好。'},{id:2,tree:'A001',date:'2026-08-20',stage:'膨大',text:'苹果正在长大，定期检查水分和病虫害。'},{id:3,tree:'A001',date:'2026-06-15',stage:'套袋',text:'给每一颗小苹果套上纸袋，保护果面。'},{id:4,tree:'A001',date:'2026-05-20',stage:'疏果',text:'留下健康的果子，给每颗苹果充足的生长空间。'},{id:5,tree:'A001',date:'2026-04-12',stage:'开花',text:'山里的苹果花开了，蜜蜂也来赴约。'},{id:6,tree:'A001',date:'2026-03-15',stage:'萌芽',text:'今年第一批小芽，迎着春风慢慢舒展。'}],orders:Array.from({length:12},(_,i)=>({id:'SL2026'+String(i+1).padStart(3,'0'),tree:id(i+16),user:i+16,year:2026,status:['待采摘','待包装','待发货','已发货','已签收','已完成'][i%6],weight:20,pack:'5斤礼盒 × 4',method:'邮寄',address:'杭州市幸福路88号（演示）',carrier:i%6>=3?'顺丰速运':'',tracking:i%6>=3?'SFDEMO'+(i+1):'',shipDate:i%6>=3?'2026-09-12':''})),tasks:[{id:1,title:'拍摄12棵苹果树的着色照片',date:'2026-09-14',done:false},{id:2,title:'为3位新用户确认认领资料',date:'2026-09-14',done:false},{id:3,title:'确认5个订单的收货地址',date:'2026-09-14',done:false},{id:4,title:'联系2位周末到园采摘的用户',date:'2026-09-14',done:false},{id:5,title:'完成15位老用户的续领回访',date:'2026-09-14',done:false}],contents:[{id:1,title:'张叔与他的第十二个丰收年',type:'果农故事',platform:'公众号',date:'2026-09-16',status:'待发布',text:'从春天的第一朵花，到秋天的第一颗红苹果，张叔一直在山里等你。',views:0,leads:0,sales:0},{id:2,title:'你认领的苹果，今天红了一点',type:'果树成长记录',platform:'朋友圈',date:'2026-09-12',status:'已发布',text:'今天上山，给大家拍了最新的果树照片。',views:1280,leads:18,sales:4}],costs:{pack:1740,logistics:2610,marketing:2800,service:1640}};
export function metrics(d:any){const histories=d.users.flatMap((u:any)=>u.history).filter((h:any)=>h.year===2026);return {total:d.trees.length,claimed:d.trees.filter((t:any)=>t.user).length,available:d.trees.filter((t:any)=>!t.user).length,users:d.users.length,revenue:histories.reduce((s:number,h:any)=>s+h.amount,0),yield:d.trees.reduce((s:number,t:any)=>s+t.yield,0),completed:d.orders.filter((o:any)=>o.status==='已完成').length,rate:(d.trees.filter((t:any)=>t.user).length/d.trees.length*100).toFixed(1),renewal:(d.users.filter((u:any)=>u.history.some((h:any)=>h.year===2025)&&u.history.some((h:any)=>h.year===2026)).length/Math.max(1,d.users.filter((u:any)=>u.history.some((h:any)=>h.year===2025)).length)*100).toFixed(0)}};
export function adopt(d:any,f:any){const tree=f.tree||d.trees.find((t:any)=>!t.user)?.id;const t=d.trees.find((t:any)=>t.id===tree);if(!t||t.user)throw Error('果树已被认领，请重新选择');if(!/^1\d{10}$/.test(f.phone))throw Error('请输入11位手机号');if(d.users.some((u:any)=>u.phone===f.phone))throw Error('该手机号已有档案，请使用不同的演示手机号');const p=d.plans.find((p:any)=>p.name===(f.plan||d.plans[0].name));const u={...f,id:Date.now(),tree,plan:p.name,amount:p.price,method:f.method||'邮寄',source:f.source||'朋友圈',willing:'待回访',history:[{year:2026,tree,amount:p.price,date:f.date,status:'陪伴中'}]};return {...d,users:[...d.users,u],trees:d.trees.map((x:any)=>x.id===tree?{...x,user:u.id}:x)}};
export function advance(d:any,id:string){const o=d.orders.find((o:any)=>o.id===id),t=d.trees.find((t:any)=>t.id===o.tree);const flow=o.method==='到园采摘'?['待成熟','待采摘','已签收','已完成']:['待成熟','待采摘','待包装','待发货','已发货','已签收','已完成'];if(o.status==='待成熟'&&t.stage!=='成熟')throw Error('请先在果树档案中确认成熟');if(o.status==='待发货'&&(!o.tracking||!o.carrier||!o.address||!o.shipDate))throw Error('请先补全快递公司、单号、地址和发货日期');const status=flow[Math.min(flow.indexOf(o.status)+1,flow.length-1)];return {...d,orders:d.orders.map((x:any)=>x.id===id?{...x,status}:x),trees:d.trees.map((x:any)=>x.id===o.tree&&status==='已完成'?{...x,stage:'已完成'}:x),users:d.users.map((u:any)=>u.id===o.user?{...u,history:u.history.map((h:any)=>h.tree===o.tree&&h.year===2026?{...h,status:status==='已完成'?'已完成':'交付中'}:h)}:u)}};
export function renew(d:any,id:number,amount:number){const u=d.users.find((x:any)=>x.id===id);if(u.history.some((h:any)=>h.year===2027))throw Error('已登记2027年续领');if(!u.history.some((h:any)=>h.year===2026&&h.status==='已完成'))throw Error('请先完成本年交付，再登记次年续领');if(amount<=0)throw Error('请填写有效金额');return {...d,users:d.users.map((x:any)=>x.id===id?{...x,willing:'已续领',history:[...x.history,{year:2027,tree:x.tree,amount,date:new Date().toISOString().slice(0,10),status:'已续领'}]}:x)}};

// Keep demonstration histories, dates and delivery states consistent.
seed.users.forEach((u,i)=>{u.date=`2026-${String(3+Math.floor(i/12)).padStart(2,'0')}-${String(i%12+1).padStart(2,'0')}`;u.history.forEach(h=>{if(h.year===2026&&h.tree===u.tree)h.date=u.date})});
seed.orders.forEach(o=>{const u=seed.users.find(u=>u.id===o.user)!;u.history.forEach(h=>{if(h.year===2026&&h.tree===o.tree)h.status=o.status==='已完成'?'已完成':'交付中'});if(o.status==='已完成')seed.trees.find(t=>t.id===o.tree)!.stage='已完成'});
export function revenueSeries(d:any){return [3,4,5,6,7,8,9].map(month=>d.users.flatMap((u:any)=>u.history).filter((h:any)=>h.year===2026&&Number(h.date.slice(5,7))<=month).reduce((s:number,h:any)=>s+h.amount,0))}

